apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  hostPath:
    path: "/data/tmp/dump" 
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
