apiVersion: v1
kind: Service
metadata:
  name: api-service
spec: # Configuração do Serviço
  selector:
    name: api-deployment # Nome do deployment!
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
